/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Estado de la API y de la base de datos
         * @description Lo usa el healthcheck de Docker: responde 503 si la base de datos no está disponible.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Todo funciona */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Salud"];
                    };
                };
                /** @description Error inesperado */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description La base de datos no responde */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Salud"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Salud: {
            /**
             * @description ok solo si todos los componentes funcionan
             * @enum {string}
             */
            estado: "ok" | "error";
            /** @enum {string} */
            api: "ok";
            /** @enum {string} */
            baseDeDatos: "ok" | "error";
        };
        Error: {
            error: {
                /** @example validacion */
                codigo: string;
                /** @example Los datos enviados no son válidos */
                mensaje: string;
                detalles?: unknown;
            };
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
